[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  colorscheme = "gruvbox"
  colorscheme_bg = "dark"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = "arrow"
  statusline_inactive_separator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = true
  filetree_direction = "left"
  bootstrap_before = "myspacevim#before"
  bootstrap_after = "myspacevim#after"
  guifont = "SauceCodePro Nerd Font Mono:h13"
  enabe_vimfiler_filetypeicon = 0
  enable_vimfiler_gitstatus = 0


# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "cycle"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

# This is an example for adding custom plugins lilydjwg/colorizer
[[custom_plugins]]
  name = "lilydjwg/colorizer"
  merged = false

[[custom_plugins]]
  name = "Xuyuanp/nerdtree-git-plugin"
  merged = false

[[layers]]
  name = "checkers"

[[layers]]
name = "lang#javascript"
auto_fix = true
enable_flow_syntax = true

[[layers]]
  name = "lang#php"

[[custom_plugins]]
  name = "arnaud-lb/vim-php-namespace"
  merged = false

[[custom_plugins]]
  name = "gcmt/taboo.vim"
  merged = false

[[custom_plugins]]
  name = "beyondwords/vim-twig"
  merged = false

[[custom_plugins]]
  name = "jwalton512/vim-blade"
  merged = false

[[layers]]
  name = "ui"
  enable_sidebar = true

[[layers]]
  name = "tools"

[[custom_plugins]]
  name = "pangloss/vim-javascript"
  merged = false
    
[[custom_plugins]]
  name = "mxw/vim-jsx"
  merged = false

[[layers]]
  name = "gtags"

[[layers]]
  name = "fzf"    

[[layers]]
  name = "lang#html"