#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  colorscheme = "vim-material"
  colorscheme_bg = "dark"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = "arrow"
  statusline_iseparator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = false
  
  # recently added 07-18-2022
  enable_sidebar = true
  enable_cursorword = false

  filetree_direction = "left"
  filemanager = "defx"
  bootstrap_before = "myspacevim#before"
  bootstrap_after = "myspacevim#after"
  autocomplete_method = "deoplete"
  
  enable_ale = true
  enable_neomake = false

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "lang#php"

[[layers]]
  name = 'gtags'

[[layers]]
  name = "git"

[[custom_plugins]]
  name = "lilydjwg/colorizer"
  merged = false

[[custom_plugins]]
  name = "arnaud-lb/vim-php-namespace"
  merged = false

[[layers]]
  name = "tools"

[[layers]]
  name = "fzf"  
  
[[layers]]
  name = "lsp"
  enable = true
  filetypes = [
    "php",
    "javascript"
  ]

[[layers]]
  name = "lang#extra"
  

[[custom_plugins]]
  name = "hzchirs/vim-material"

[[custom_plugins]]
  name = "vim-airline/vim-airline"

[[custom_plugins]]
  name = "vim-airline/vim-airline-themes"

[[layers]]
	name = "checkers"

[[custom_plugins]]
  name = "Shougo/vimproc.vim"

[[custom_plugins]]
  name = "stephpy/vim-php-cs-fixer"

[[custom_plugins]]
  name = "nvim-lua/popup.nvim"

[[custom_plugins]]
  name = "nvim-lua/plenary.nvim"
  
# [[custom_plugins]]
  # name = "nvim-telescope/telescope.nvim"

[[custom_plugins]]
  name = "kyazdani42/nvim-web-devicons"

# [[custom_plugins]]
  # name = "npxbr/glow.nvim"
  
[[custom_plugins]]
  name = "dense-analysis/ale"

[[layers]]
  name = "lang#markdown"

# [[layers]]
  # name = "debug"

[[layers]]
  name = "lang#javascript"

[[custom_plugins]]
  name = "nelsyeung/twig.vim"

[[custom_plugins]]
  name = "wakatime/vim-wakatime"

[[custom_plugins]]
  name = "kevinhwang91/nvim-hlslens"

[[custom_plugins]]
  name = "neovim/nvim-lspconfig"

[[custom_plugins]]
  name = "kabouzeid/nvim-lspinstall"

