# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
	automatic_update = true
  colorscheme = "vim-material"
  colorscheme_bg = "dark"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = "arrow"
  statusline_inactive_separator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = true
  guifont = "SauceCodePro Nerd Font Mono:h11"
  filetree_direction = "left"
  bootstrap_before = "myspacevim#before"
  bootstrap_after = "myspacevim#after"
  enable_ale = true
  enable_neomake = false
  # autocomplete_method = "coc"
  autocomplete_method = "deoplete"
  default_indent = 2
  expand_tab = false
  filemanager = "defx"
	snippet_engine = "ultisnips"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = "git"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'fzf'

[[custom_plugins]]
name = "lilydjwg/colorizer"
merged = false

[[layers]]
name = "lang#javascript"
auto_fix = false
enable_flow_syntax = false

[[layers]]
name = "lang#php"

[[custom_plugins]]
name = "arnaud-lb/vim-php-namespace"
merged = false

[[custom_plugins]]
name = "beyondwords/vim-twig"
merged = false

[[custom_plugins]]
name = "jwalton512/vim-blade"
merged = false

[[layers]]
name = "tools"

[[custom_plugins]]
name = "pangloss/vim-javascript"
merged = false
    
[[custom_plugins]]
name = "maxmellon/vim-jsx-pretty"
merged = false

[[layers]]
name = "gtags"

[[layers]]
name = "fzf"    

[[layers]]
name = "lang#html"

[[layers]]
name = "lang#vue"

[[layers]]
name = "lsp"
enable = true
filetypes = [
  "php",
  "javascript"
]

[[custom_plugins]]
  name = "Rican7/php-doc-modded"
  merged = false

[[layers]]
  name = "lang#extra"

[[custom_plugins]]
  name = "hzchirs/vim-material"

[[custom_plugins]]
  name = "vim-airline/vim-airline"

[[custom_plugins]]
  name = "vim-airline/vim-airline-themes"

[[layers]]
	name = "checkers"

[[custom_plugins]]
  name = "Shougo/vimproc.vim"

[[custom_plugins]]
  name = "stephpy/vim-php-cs-fixer"

[[custom_plugins]]
  name = "nvim-lua/popup.nvim"

[[custom_plugins]]
  name = "nvim-lua/plenary.nvim"

[[custom_plugins]]
  name = "nvim-telescope/telescope.nvim"

[[custom_plugins]]
  name = "kyazdani42/nvim-web-devicons"

# [[custom_plugins]]
  # name = "kevinhwang91/nvim-hlslens"

[[custom_plugins]]
  name = "npxbr/glow.nvim"

[[custom_plugins]]
  name = "npxbr/glow.nvim"

[[custom_plugins]]
  name = "dense-analysis/ale"

[[layers]]
  name = "lang#java"

[[layers]]
  name = "lang#dart"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "debug"
